### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=fee

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#20]
https://docs.google.com/document/d/1CzA8r-XsjFUQFRbuc9PT96lvDAZwuyPvbMmHLCQ4JTA/edit

**Comment by elgholston** [comment]
Updated

**Comment by heymrhayes** [comment]
Lots of work on this - both on the page and the back-end - but it will be much more flexible and easy to modify next year.

**Comment by elgholston** [comment]
Got it.

On Jul 29, 2017 11:12 AM, "heymrhayes" <notifications@github.com> wrote:

Lots of work on this - both on the page and the back-end - but it will be
much more flexible and easy to modify next year.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/heymrhayes/quickStart2017/issues/20#issuecomment-318841042>,
or mute the thread
